create or replace PROCEDURE "INDUSTRIAL_RENDIMIENTO_BULKS" IS

--Realizado por Ángel Jesús Calzas Durán
--Versión: 4
--Fecha: 1/7/2026

-- DEFINICIÓN DE VARIABLES
V_SQL                   VARCHAR2(32000);

-------------------------------------------------
-- Comienzo de la lógica
-------------------------------------------------

BEGIN

-- Truncamos la tabla
EXECUTE IMMEDIATE 'TRUNCATE TABLE ANL_IND_RENDIMIENTO_BULK';
COMMIT;

-- Insertamos los rendimientos de los bulks
V_SQL:='
INSERT INTO ANL_IND_RENDIMIENTO_BULK (NUM_ORDEN_BULK, LOTE,ESTADO_ORDEN_BULK,FLG_ENVIO_A_TERCERO,ESTADO_RENDIMIENTO_BULK,ESTADO_RENDIMIENTO_ACON,ALMACEN,NUMERO_ACTIVO_BULK,DESC_ACTIVO_BULK,
                                      COD_CORTO_PROD_BULK,COD_LARGO_PROD_BULK,LOCAL_PRODUCT_NAME,BRAND,REGULATORY_STATUS,TIPO_PRODUCTO,SUBTIPO_PRODUCTO,
                                      FECHA_SOLICITADA_BULK,FECHA_FINALIZACION_BULK,FECHA_ORDEN_BULK,
                                      CANTIDAD_ORDENADA_BULK,CANTIDAD_ENVIADA_BULK,UNIDADES_BULK,DENSIDAD_BULK,RENDIMIENTO_BULK,
                                      NUM_ORDEN_ACON,LOTE_ACON,ESTADO_ORDEN_ACON,FECHA_FINALIZACION_ACON,ALMACEN_ACON,NUMERO_ACTIVO_ACON,DESC_ACTIVO_ACON,COD_LARGO_PROD_ACON,LOCAL_PRODUCT_NAME_ACON,FORMATO_ACON,
                                      UNIDADES_ACON,CANTIDAD_ACON_NO_TERCERO,CANTIDAD_ACON_TERCERO,
                                      RENDIMIENTO_ACON,RENDIMIENTO_GLOBAL)                               
SELECT
NUM_ORDEN_BULK, 
LOTE,
ESTADO_ORDEN_BULK,
CASE WHEN (LISTAGG(ALMACEN_ACON,'';'') OVER (PARTITION BY NUM_ORDEN_BULK)=''CL1T'' OR LISTAGG(ALMACEN_ACON,'';'') OVER (PARTITION BY NUM_ORDEN_BULK) LIKE ''%CL1T%'')
          AND NOT (LISTAGG(ALMACEN_ACON,'';'') OVER (PARTITION BY NUM_ORDEN_BULK) LIKE ''%CL1;%'' OR LISTAGG(ALMACEN_ACON,'';'') OVER (PARTITION BY NUM_ORDEN_BULK) LIKE ''%;CL1'')
          THEN ''Solo envío a terceros''
     WHEN LISTAGG(ALMACEN_ACON,'';'') OVER (PARTITION BY NUM_ORDEN_BULK) NOT LIKE ''%CL1T%''
          THEN ''Sin envío a terceros''
     WHEN LISTAGG(ALMACEN_ACON,'';'') OVER (PARTITION BY NUM_ORDEN_BULK) IS NULL THEN ''-''
     ELSE ''Con envío a terceros''
END AS FLG_ENVIO_A_TERCERO,
CASE WHEN LISTAGG(ESTADO_RENDIMIENTO,'';'') OVER (PARTITION BY NUM_ORDEN_BULK) LIKE ''%Sin orden acondicionamiento%'' THEN ''Sin orden acondicionamiento''
     WHEN LISTAGG(ESTADO_RENDIMIENTO,'';'') OVER (PARTITION BY NUM_ORDEN_BULK) LIKE ''%Sin formato del producto acondicionado o formato incorrecto y sin densidad del bulk%'' THEN ''Sin formato del producto acondicionado o formato incorrecto y sin densidad del bulk''
     WHEN LISTAGG(ESTADO_RENDIMIENTO,'';'') OVER (PARTITION BY NUM_ORDEN_BULK) LIKE ''%Sin formato del producto acondicionado o formato incorrecto%'' AND LISTAGG(ESTADO_RENDIMIENTO,'';'') OVER (PARTITION BY NUM_ORDEN_BULK) NOT LIKE ''%Sin densidad del bulk%'' THEN ''Sin formato del producto acondicionado o formato incorrecto''
     WHEN LISTAGG(ESTADO_RENDIMIENTO,'';'') OVER (PARTITION BY NUM_ORDEN_BULK) LIKE ''%Sin densidad del bulk%'' THEN ''Sin densidad del bulk''
     ELSE ''Correcto''
END AS ESTADO_RENDIMIENTO_BULK,
ESTADO_RENDIMIENTO AS ESTADO_RENDIMIENTO_ACON,
ALMACEN, 
NUMERO_ACTIVO_BULK,
DESC_ACTIVO_BULK,
COD_CORTO_PROD_BULK, 
COD_LARGO_PROD_BULK, 
LOCAL_PRODUCT_NAME, 
BRAND, 
REGULATORY_STATUS,
TIPO_PRODUCTO,
SUBTIPO_PRODUCTO,
FECHA_SOLICITADA_BULK,
FECHA_FINALIZACION_BULK,
FECHA_ORDEN_BULK,
CANTIDAD_ORDENADA_BULK,
CANTIDAD_ENVIADA_BULK,
UNIDADES_BULK,
DENSIDAD_BULK,
RENDIMIENTO_BULK,
NUM_ORDEN_ACON,
LOTE_ACON,
ESTADO_ORDEN_ACON,
FECHA_FINALIZACION_ACON,
ALMACEN_ACON,
NUMERO_ACTIVO_ACON,
DESC_ACTIVO_ACON,
COD_LARGO_PROD_ACON,
LOCAL_PRODUCT_NAME_ACON,
FORMATO_ACON,
UNIDADES_ACON,
CANTIDAD_ACON_NO_TERCERO,
CANTIDAD_ACON_TERCERO,
CASE WHEN SUM(CASE WHEN CANTIDAD_ACON IS NULL THEN 1 ELSE 0 END) OVER (PARTITION BY NUM_ORDEN_BULK)=0 AND (CANTIDAD_ENVIADA_BULK-NVL(SUM(CANTIDAD_ACON_TERCERO) OVER (PARTITION BY NUM_ORDEN_BULK),0))<>0 THEN SUM(CANTIDAD_ACON_NO_TERCERO) OVER (PARTITION BY NUM_ORDEN_BULK)/(CANTIDAD_ENVIADA_BULK-NVL(SUM(CANTIDAD_ACON_TERCERO) OVER (PARTITION BY NUM_ORDEN_BULK),0)) END AS RENDIMIENTO_ACON,
CASE WHEN SUM(CASE WHEN CANTIDAD_ACON IS NULL THEN 1 ELSE 0 END) OVER (PARTITION BY NUM_ORDEN_BULK)=0 AND (CANTIDAD_ORDENADA_BULK-NVL(SUM(CANTIDAD_ACON_TERCERO) OVER (PARTITION BY NUM_ORDEN_BULK),0))<>0 THEN SUM(CANTIDAD_ACON_NO_TERCERO) OVER (PARTITION BY NUM_ORDEN_BULK)/(CANTIDAD_ORDENADA_BULK-NVL(SUM(CANTIDAD_ACON_TERCERO) OVER (PARTITION BY NUM_ORDEN_BULK),0)) END AS RENDIMIENTO_GLOBAL
from
(
SELECT
CASE 
WHEN NUM_ORDEN_ACON IS NULL 
THEN ''Sin orden acondicionamiento''
WHEN (UNIDADES_FORMATO_ACON NOT IN (''ml'', ''gr'', ''kg'') OR UNIDADES_FORMATO_ACON IS NULL) AND DENSIDAD_BULK IS NOT NULL
THEN ''Sin formato del producto acondicionado o formato incorrecto''
WHEN UNIDADES_FORMATO_ACON IN (''ml'', ''gr'', ''kg'') AND DENSIDAD_BULK IS NULL
THEN ''Sin densidad del bulk''
WHEN (UNIDADES_FORMATO_ACON NOT IN (''ml'', ''gr'', ''kg'') OR UNIDADES_FORMATO_ACON IS NULL) AND DENSIDAD_BULK IS NULL
THEN ''Sin formato del producto acondicionado o formato incorrecto y sin densidad del bulk''
ELSE ''Correcto''
END AS ESTADO_RENDIMIENTO
,
P.*,
P.CANTIDAD_ENVIADA_ACON AS UNIDADES_ACON,
P.CANTIDAD_ENVIADA_ACON*P.DENSIDAD_BULK*P.CANTIDAD_FORMATO_ACON/(CASE WHEN UNIDADES_FORMATO_ACON IN (''ml'', ''gr'') THEN 1000 ELSE CASE WHEN UNIDADES_FORMATO_ACON IN (''kg'') THEN 1 END END) AS CANTIDAD_ACON,
P.CANTIDAD_ENVIADA_ACON_NO_TERCERO*P.DENSIDAD_BULK*P.CANTIDAD_FORMATO_ACON/(CASE WHEN UNIDADES_FORMATO_ACON IN (''ml'', ''gr'') THEN 1000 ELSE CASE WHEN UNIDADES_FORMATO_ACON IN (''kg'') THEN 1 END END) AS CANTIDAD_ACON_NO_TERCERO,
--P.CANTIDAD_ENVIADA_ACON_TERCERO*P.DENSIDAD_BULK*P.CANTIDAD_FORMATO_ACON/(CASE WHEN UNIDADES_FORMATO_ACON IN (''ml'', ''gr'') THEN 1000 ELSE 1 END) AS CANTIDAD_ACON_TERCERO
CASE WHEN CANTTERC.WMUM=''KG'' THEN CANTTERC.WMTRQT/10000 WHEN CANTTERC.WMUM=''UN'' THEN (CANTTERC.WMTRQT/10000)*P.DENSIDAD_BULK*P.CANTIDAD_FORMATO_ACON/(CASE WHEN UNIDADES_FORMATO_ACON IN (''ml'', ''gr'') THEN 1000 ELSE CASE WHEN UNIDADES_FORMATO_ACON IN (''kg'') THEN 1 END END) END AS CANTIDAD_ACON_TERCERO
FROM
(
SELECT 
A.*,  
TRIM(B.WALOTN) AS LOTE_ACON,
B.WASRST AS ESTADO_ORDEN_ACON,
to_number(to_char(date_conversion.from_julian(B.WASTRX),''YYYYMMDD'')) AS FECHA_FINALIZACION_ACON,
TRIM(B.WAITM) AS COD_CORTO_PROD_ACON, 
TRIM(B.WALITM) AS COD_LARGO_PROD_ACON,
trim(NOMACON.IMDSC1)|| '' '' || trim(NOMACON.IMDSC2) AS LOCAL_PRODUCT_NAME_ACON, 
CASE WHEN B.WASTRX<>0 THEN (CASE WHEN TRIM(B.WAMCU) IN (''CL1T'') THEN B.WAUORG/10000 ELSE B.WASOQS/10000 END) END AS CANTIDAD_ENVIADA_ACON,
CASE WHEN B.WASTRX<>0 THEN (CASE WHEN TRIM(B.WAMCU) NOT IN (''CL1T'') THEN B.WASOQS/10000 END) END AS CANTIDAD_ENVIADA_ACON_NO_TERCERO,
CASE WHEN B.WASTRX<>0 THEN (CASE WHEN TRIM(B.WAMCU) IN (''CL1T'') THEN B.WAUORG/10000 END) END AS CANTIDAD_ENVIADA_ACON_TERCERO,
TRIM(B.WAMCU) AS ALMACEN_ACON,
CASE WHEN TO_NUMBER(TRIM(C.AGTRQT))>0 THEN TO_NUMBER(TRIM(C.AGTRQT))/10000 END AS DENSIDAD_BULK,
TRIM(E.DRDL01) AS FORMATO_ACON,
CASE WHEN instr(E.DRDL01,''x'')>0 
THEN TO_NUMBER(SUBSTR(E.DRDL01,1,instr(E.DRDL01,'' '')-1))*TO_NUMBER(SUBSTR(SUBSTR(E.DRDL01,instr(E.DRDL01,''x'')+2),1,instr(SUBSTR(E.DRDL01,instr(E.DRDL01,''x'')+2),'' '')-1))
ELSE (CASE WHEN REGEXP_LIKE(SUBSTR(E.DRDL01,1,1),''^[0-9]+$'') THEN CAST(TRIM(REPLACE(REPLACE(E.DRDL01,''ml'',''''),''gr'','''')) AS NUMBER DEFAULT NULL ON CONVERSION ERROR) ELSE 1 END)
END AS CANTIDAD_FORMATO_ACON,
TRIM(CASE WHEN instr(E.DRDL01,''x'')>0 
THEN SUBSTR(SUBSTR(E.DRDL01,instr(E.DRDL01,''x'')+2),instr(SUBSTR(E.DRDL01,instr(E.DRDL01,''x'')+2),'' '')+1)
ELSE CASE WHEN E.DRDL01 NOT IN (''BULK'',''N/A'',''NO APLICA'',''pack 1 + 1'') THEN TRIM(REPLACE(REGEXP_REPLACE(E.DRDL01,''[0-9]+''),'','','''')) END
END) AS UNIDADES_FORMATO_ACON,
RBULK.NUMERO_ACTIVO AS NUMERO_ACTIVO_BULK,
RBULK.DESC_ACTIVO AS DESC_ACTIVO_BULK,
RACON.NUMERO_ACTIVO AS NUMERO_ACTIVO_ACON,
RACON.DESC_ACTIVO AS DESC_ACTIVO_ACON
FROM
(
SELECT DISTINCT 
ORD.WADOCO AS NUM_ORDEN_BULK, 
TRIM(ORD.WALOTN) LOTE,
ORD.WASRST ESTADO_ORDEN_BULK,
TRIM(ORD.WAITM) AS COD_CORTO_PROD_BULK, 
TRIM(ORD.WALITM) AS COD_LARGO_PROD_BULK, 
TRIM(ORD.WAMCU) AS ALMACEN, 
trim(NOM.IMDSC1)|| '' '' || trim(NOM.IMDSC2) AS LOCAL_PRODUCT_NAME, 
TRIM(NOM.IMSRP1) AS BRAND, 
TRIM(NOM.IMSRP6) AS REGULATORY_STATUS,
TRIM(NOM.IMPRP1) AS TIPO_PRODUCTO,
TRIM(NOM.IMPRP2) AS SUBTIPO_PRODUCTO,
--to_number(to_char(date_conversion.from_julian(ORD.WASTRT),''YYYYMMDD'')) as FECHA_INICIAL_BULK,
to_number(to_char(date_conversion.from_julian(ORD.WADRQJ),''YYYYMMDD'')) as FECHA_SOLICITADA_BULK,
--to_number(to_char(date_conversion.from_julian(ORD.WADPL),''YYYYMMDD'')) as FECHA_DISPONIBILIDAD_BULK, 
to_number(to_char(date_conversion.from_julian(ORD.WASTRX),''YYYYMMDD'')) AS FECHA_FINALIZACION_BULK,
to_number(to_char(date_conversion.from_julian(ORD.WATRDJ),''YYYYMMDD'')) AS FECHA_ORDEN_BULK,
ORD.WAUORG/10000 CANTIDAD_ORDENADA_BULK,
ORD.WASOQS/10000 CANTIDAD_ENVIADA_BULK,
ORD.WAUOM AS UNIDADES_BULK,
ORD.WASOQS/ORD.WAUORG RENDIMIENTO_BULK,
CAR.NUM_ORD /*TRIM(CAR.ILDOCO)*/ AS NUM_ORDEN_ACON
FROM STG_JDE_IFCSA_F4801 ORD
LEFT JOIN STG_JDE_IFCSA_F4101_ADT NOM
ON ORD.WAITM = NOM.IMITM
--LEFT JOIN CLABS_STG_PRO.STG_JDE_IFCSA_F4111 CAR
--ON TRIM(ORD.WALOTN) = TRIM(CAR.ILLOTN) AND ORD.WAITM=CAR.ILITM AND TRIM(CAR.ILDCT)=''IM''
/**/
LEFT JOIN 
(
SELECT DISTINCT TO_CHAR(TRIM(REL.IXLITM)) AS COD_PROD, TO_CHAR(TRIM(WALOTN)) AS NUM_LOTE, TO_CHAR(WADOCO) AS NUM_ORD
FROM 
STG_JDE_IFCSA_F4801 ORD
LEFT JOIN STG_JDE_IFCSA_F4101_ADT NOM
ON ORD.WAITM = NOM.IMITM
LEFT JOIN CLABS_STG_PRO.STG_JDE_IFCSA_F3002_ADT REL
ON TRIM(ORD.WALITM)=TRIM(REL.IXKITL)
LEFT JOIN (SELECT DISTINCT TO_CHAR(TRIM(CAR.ILLOTN)) AS NUM_LOTE, TO_CHAR(TRIM(CAR.ILDOCO)) AS NUM_ORD
            FROM 
            CLABS_STG_PRO.STG_JDE_IFCSA_F4111 CAR
            WHERE TRIM(CAR.ILDCT)=''IM''
            ) CAR_AUX
ON TO_CHAR(TRIM(WALOTN))=CAR_AUX.NUM_LOTE AND TO_CHAR(TRIM(WADOCO))=CAR_AUX.NUM_ORD
WHERE TRIM(NOM.IMPRP2)<>''BLK'' AND CAR_AUX.NUM_ORD IS NULL 
UNION
SELECT TO_CHAR(TRIM(CAR.ILLITM)) AS COD_PROD, TO_CHAR(TRIM(CAR.ILLOTN)) AS NUM_LOTE, TO_CHAR(TRIM(CAR.ILDOCO)) AS NUM_ORD
FROM 
CLABS_STG_PRO.STG_JDE_IFCSA_F4111 CAR
WHERE TRIM(CAR.ILDCT)=''IM'' 
) CAR
ON TRIM(ORD.WALOTN)=CAR.NUM_LOTE AND TRIM(ORD.WALITM)=CAR.COD_PROD
/**/
WHERE TRIM(NOM.IMPRP2)=''BLK''
AND ORD.WASOQS>0
) A
LEFT JOIN STG_JDE_IFCSA_F4801 B
ON A.NUM_ORDEN_ACON=B.WADOCO
LEFT JOIN CLABS_STG_PRO.STG_JDE_IFCSA_F5541AGR C
ON A.COD_CORTO_PROD_BULK=TRIM(C.AGITM)
LEFT JOIN CLABS_STG_PRO.STG_JDE_IFCSA_F5541AGR D
ON B.WAITM=TRIM(D.AGITM)
LEFT JOIN CLABS_STG_PRO.STG_JDE_IFCSA_F0005 E
ON TRIM(D.AGRP23)=TRIM(E.DRKY) AND E.DRSY=''55'' AND E.DRRT=''10''
LEFT JOIN STG_JDE_IFCSA_F4101_ADT NOMACON
ON B.WAITM = NOMACON.IMITM
LEFT JOIN 
(
SELECT
WLDOCO AS NUM_ORDEN,
WLOPSQ/100 AS FASE,
WLAPID AS NUMERO_UNIDAD, 
WLNUMB AS NUMERO_ACTIVO,
UPPER(TRIM(FADL01||FADL02)) AS DESC_ACTIVO
FROM
"CLABS_STG_PRO"."STG_JDE_IFCSA_F3112" A
LEFT JOIN 
"CLABS_STG_PRO"."STG_JDE_IFCSA_F1201" B
ON A.WLNUMB=B.FANUMB
where TO_CHAR(WLOPSQ) LIKE ''102%'' AND WLNUMB<>0
) RBULK
ON A.NUM_ORDEN_BULK=RBULK.NUM_ORDEN
LEFT JOIN 
(
SELECT
WLDOCO AS NUM_ORDEN,
WLOPSQ/100 AS FASE,
WLAPID AS NUMERO_UNIDAD, 
WLNUMB AS NUMERO_ACTIVO,
UPPER(TRIM(FADL01||FADL02)) AS DESC_ACTIVO
FROM
"CLABS_STG_PRO"."STG_JDE_IFCSA_F3112" A
LEFT JOIN 
"CLABS_STG_PRO"."STG_JDE_IFCSA_F1201" B
ON A.WLNUMB=B.FANUMB
where TO_CHAR(WLOPSQ/100)=''205'' AND WLNUMB<>0
) RACON
ON A.NUM_ORDEN_ACON=RACON.NUM_ORDEN
) P
LEFT JOIN 
(SELECT WMDOCO, WMLOTN, WMUM, SUM(WMTRQT) AS WMTRQT
FROM CLABS_STG_PRO.STG_JDE_IFCSA_F3111
GROUP BY WMDOCO, WMLOTN, WMUM
) CANTTERC
ON P.NUM_ORDEN_ACON=TRIM(CANTTERC.WMDOCO) AND CASE WHEN LENGTH(TRIM(P.LOTE_ACON))<>6 THEN TRIM(P.LOTE) ELSE TRIM(P.LOTE_ACON) END=TRIM(CANTTERC.WMLOTN)
AND P.CANTIDAD_ENVIADA_ACON_TERCERO IS NOT NULL
)
WHERE ALMACEN=''CL1''
AND FECHA_FINALIZACION_BULK>=20260101
'
;

EXECUTE IMMEDIATE V_SQL;
COMMIT;


END INDUSTRIAL_RENDIMIENTO_BULKS;
