create or replace PROCEDURE                 "INDUSTRIAL_UNIDADES_FABRICADAS" AS
BEGIN

execute immediate 'truncate table ANL_IND_UNIDADES_FABRICADAS';

-- Un pivot necesario para la manera en la que se quiere visualizar en Tableau
INSERT INTO ANL_IND_UNIDADES_FABRICADAS (NUM_ORDEN,FECHA_FINALIZACION,AÑO,MES,ALMACEN,NUM_LOTE,COD_CORTO_PROD,COD_LARGO_PROD,
LOCAL_PRODUCT_NAME,TIPO_PRODUCTO,USUARIO,METRICA,VALOR_METRICA,DATE_UPD, SUBTIPO_PRODUCTO, CLASIFICACION_FABRICA)

SELECT * FROM 
(
WITH FAB AS
(
SELECT A.*, B.IMPRP2 AS SUBTIPO_PRODUCTO FROM 
(
select NUM_ORDEN,FECHA_FINALIZACION,AÑO,MES,ALMACEN,NUM_LOTE,COD_CORTO_PROD,COD_LARGO_PROD,LOCAL_PRODUCT_NAME,TIPO_PRODUCTO,USUARIO,
'Uds Fabricadas' METRICA,nvl(UDS_FABRICADAS,0) VALOR_METRICA, DATE_UPD
FROM clabs_std_pro.std_ind_uds_costes
WHERE DATA_SOURCE=1 AND 
( AÑO<EXTRACT(year FROM ADD_MONTHS(SYSDATE,-1))
OR
AÑO||case when length(MES)<2 then '0'||to_char(MES) else to_char(MES) end
 <=EXTRACT(YEAR FROM ADD_MONTHS(SYSDATE,-1))||(case when length(to_char(EXTRACT(MONTH FROM ADD_MONTHS(SYSDATE,-1))))<2 then '0'||to_char(EXTRACT(MONTH FROM ADD_MONTHS(SYSDATE,-1)))
 else to_char(EXTRACT(MONTH FROM ADD_MONTHS(SYSDATE,-1))) end))
UNION ALL
-- COSTE A1 DE LAS UDS FABRICADAS
select NUM_ORDEN,FECHA_FINALIZACION,AÑO,MES,ALMACEN,NUM_LOTE,COD_CORTO_PROD,COD_LARGO_PROD,LOCAL_PRODUCT_NAME,TIPO_PRODUCTO,USUARIO,
'Coste A1' METRICA,nvl(COSTE_UNIDADES,0) VALOR_METRICA, DATE_UPD
FROM clabs_std_pro.std_ind_uds_costes
WHERE DATA_SOURCE=2 AND TIPO_COSTE='A1' AND
( AÑO<EXTRACT(year FROM ADD_MONTHS(SYSDATE,-1))
OR
AÑO||case when length(MES)<2 then '0'||to_char(MES) else to_char(MES) end
 <=EXTRACT(YEAR FROM ADD_MONTHS(SYSDATE,-1))||(case when length(to_char(EXTRACT(MONTH FROM ADD_MONTHS(SYSDATE,-1))))<2 then '0'||to_char(EXTRACT(MONTH FROM ADD_MONTHS(SYSDATE,-1)))
 else to_char(EXTRACT(MONTH FROM ADD_MONTHS(SYSDATE,-1))) end))
 UNION ALL
-- COSTE B1 DE LAS UDS FABRICADAS
select NUM_ORDEN,FECHA_FINALIZACION,AÑO,MES,ALMACEN,NUM_LOTE,COD_CORTO_PROD,COD_LARGO_PROD,LOCAL_PRODUCT_NAME,TIPO_PRODUCTO,USUARIO,
'Coste B1' METRICA,nvl(COSTE_UNIDADES,0) VALOR_METRICA, DATE_UPD
FROM clabs_std_pro.std_ind_uds_costes
WHERE DATA_SOURCE=2 AND TIPO_COSTE='B1' AND
( AÑO<EXTRACT(year FROM ADD_MONTHS(SYSDATE,-1))
OR
AÑO||case when length(MES)<2 then '0'||to_char(MES) else to_char(MES) end
 <=EXTRACT(YEAR FROM ADD_MONTHS(SYSDATE,-1))||(case when length(to_char(EXTRACT(MONTH FROM ADD_MONTHS(SYSDATE,-1))))<2 then '0'||to_char(EXTRACT(MONTH FROM ADD_MONTHS(SYSDATE,-1)))
 else to_char(EXTRACT(MONTH FROM ADD_MONTHS(SYSDATE,-1))) end))
 UNION ALL
-- COSTE D1 DE LAS UDS FABRICADAS
select NUM_ORDEN,FECHA_FINALIZACION,AÑO,MES,ALMACEN,NUM_LOTE,COD_CORTO_PROD,COD_LARGO_PROD,LOCAL_PRODUCT_NAME,TIPO_PRODUCTO,USUARIO,
'Coste D1' METRICA,nvl(COSTE_UNIDADES,0) VALOR_METRICA, DATE_UPD
FROM clabs_std_pro.std_ind_uds_costes
WHERE DATA_SOURCE=2 AND TIPO_COSTE='D1' AND
( AÑO<EXTRACT(year FROM ADD_MONTHS(SYSDATE,-1))
OR
AÑO||case when length(MES)<2 then '0'||to_char(MES) else to_char(MES) end
 <=EXTRACT(YEAR FROM ADD_MONTHS(SYSDATE,-1))||(case when length(to_char(EXTRACT(MONTH FROM ADD_MONTHS(SYSDATE,-1))))<2 then '0'||to_char(EXTRACT(MONTH FROM ADD_MONTHS(SYSDATE,-1)))
 else to_char(EXTRACT(MONTH FROM ADD_MONTHS(SYSDATE,-1))) end))
  UNION ALL
-- COSTE X3 DE LAS UDS FABRICADAS  
select NUM_ORDEN,FECHA_FINALIZACION,AÑO,MES,ALMACEN,NUM_LOTE,COD_CORTO_PROD,COD_LARGO_PROD,LOCAL_PRODUCT_NAME,TIPO_PRODUCTO,USUARIO,
'Coste X3' METRICA,nvl(COSTE_UNIDADES,0) VALOR_METRICA,DATE_UPD
FROM clabs_std_pro.std_ind_uds_costes
WHERE DATA_SOURCE=2 AND TIPO_COSTE='X3' AND
( AÑO<EXTRACT(year FROM ADD_MONTHS(SYSDATE,-1))
OR
AÑO||case when length(MES)<2 then '0'||to_char(MES) else to_char(MES) end
 <=EXTRACT(YEAR FROM ADD_MONTHS(SYSDATE,-1))||(case when length(to_char(EXTRACT(MONTH FROM ADD_MONTHS(SYSDATE,-1))))<2 then '0'||to_char(EXTRACT(MONTH FROM ADD_MONTHS(SYSDATE,-1)))
 else to_char(EXTRACT(MONTH FROM ADD_MONTHS(SYSDATE,-1))) end))
UNION ALL
-- DESVIACIONES MATERIALES CANTIDAD EMBARCADA
select NUM_ORDEN,FECHA_FINALIZACION,AÑO,MES,ALMACEN,NUM_LOTE,COD_CORTO_PROD,COD_LARGO_PROD,LOCAL_PRODUCT_NAME,TIPO_PRODUCTO,USUARIO,
'Desv. Mat' METRICA,nvl(DIF_COSTE_MAT,0) VALOR_METRICA, DATE_UPD
FROM clabs_std_pro.std_ind_desviaciones_costes
WHERE 
( AÑO<EXTRACT(year FROM ADD_MONTHS(SYSDATE,-1))
OR
AÑO||case when length(MES)<2 then '0'||to_char(MES) else to_char(MES) end
 <=EXTRACT(YEAR FROM ADD_MONTHS(SYSDATE,-1))||(case when length(to_char(EXTRACT(MONTH FROM ADD_MONTHS(SYSDATE,-1))))<2 then '0'||to_char(EXTRACT(MONTH FROM ADD_MONTHS(SYSDATE,-1)))
 else to_char(EXTRACT(MONTH FROM ADD_MONTHS(SYSDATE,-1))) end))
 UNION ALL
-- DESVIACIONES MANO DE OBRA CANTIDAD EMBARCADA
select NUM_ORDEN,FECHA_FINALIZACION,AÑO,MES,ALMACEN,NUM_LOTE,COD_CORTO_PROD,COD_LARGO_PROD,LOCAL_PRODUCT_NAME,TIPO_PRODUCTO,USUARIO,
'Desv. Mdo' METRICA,nvl(DIF_COSTE_MDO,0) VALOR_METRICA, DATE_UPD
FROM clabs_std_pro.std_ind_desviaciones_costes
WHERE 
( AÑO<EXTRACT(year FROM ADD_MONTHS(SYSDATE,-1))
OR
AÑO||case when length(MES)<2 then '0'||to_char(MES) else to_char(MES) end
 <=EXTRACT(YEAR FROM ADD_MONTHS(SYSDATE,-1))||(case when length(to_char(EXTRACT(MONTH FROM ADD_MONTHS(SYSDATE,-1))))<2 then '0'||to_char(EXTRACT(MONTH FROM ADD_MONTHS(SYSDATE,-1)))
 else to_char(EXTRACT(MONTH FROM ADD_MONTHS(SYSDATE,-1))) end))
  UNION ALL
-- DESVIACIONES SERVICIO CANTIDAD EMBARCADA
select NUM_ORDEN,FECHA_FINALIZACION,AÑO,MES,ALMACEN,NUM_LOTE,COD_CORTO_PROD,COD_LARGO_PROD,LOCAL_PRODUCT_NAME,TIPO_PRODUCTO,USUARIO,
'Desv. Serv' METRICA,nvl(DIF_COSTE_SERV,0) VALOR_METRICA, DATE_UPD
FROM clabs_std_pro.std_ind_desviaciones_costes
WHERE 
( AÑO<EXTRACT(year FROM ADD_MONTHS(SYSDATE,-1))
OR
AÑO||case when length(MES)<2 then '0'||to_char(MES) else to_char(MES) end
 <=EXTRACT(YEAR FROM ADD_MONTHS(SYSDATE,-1))||(case when length(to_char(EXTRACT(MONTH FROM ADD_MONTHS(SYSDATE,-1))))<2 then '0'||to_char(EXTRACT(MONTH FROM ADD_MONTHS(SYSDATE,-1)))
 else to_char(EXTRACT(MONTH FROM ADD_MONTHS(SYSDATE,-1))) end))
 )
 A
 LEFT JOIN CLABS_STG_PRO.STG_JDE_IFCSA_F4101_ADT B
 ON TRIM(A.COD_LARGO_PROD)=TRIM(B.IMLITM)
 ),
COD_BASE AS(
    SELECT COD_LARGO_PROD AS COD_BASE,
            MAX(TIPO_PRODUCTO) AS TIPO_BASE
    FROM FAB
    GROUP BY COD_LARGO_PROD
),
COD_CL1 AS(
    SELECT DISTINCT F.COD_LARGO_PROD
    FROM FAB F
    LEFT JOIN COD_BASE CB ON CB.COD_BASE = REGEXP_REPLACE(F.COD_LARGO_PROD, '-00[0-9]$', '') 
    WHERE F.ALMACEN = 'CL1' AND REGEXP_LIKE(F.COD_LARGO_PROD, '-00(2|9)$')
    AND F.TIPO_PRODUCTO = 'PS' AND CB.TIPO_BASE IN ('PR','PT')
)
SELECT 
    F.*,
    (NVL(AUX.CLASIFICACION_FABRICA,
    CASE WHEN F.FECHA_FINALIZACION > 20260000 THEN
    (
    CASE 
        ----------------------------------------- ALMACEN CL1 --------------------------------------------------
        WHEN F.ALMACEN = 'CL1' AND F.TIPO_PRODUCTO = 'PS' AND F.SUBTIPO_PRODUCTO = 'BLK' AND F.COD_LARGO_PROD LIKE '%-001%' 
        THEN 'KGS FABRICADOS'
        WHEN F.ALMACEN = 'CL1' AND F.TIPO_PRODUCTO = 'PT' AND F.SUBTIPO_PRODUCTO = 'PT' AND F.COD_LARGO_PROD LIKE '%-007%'
        THEN 'KGS FABRICADOS'
        WHEN F.ALMACEN = 'CL1' AND F.TIPO_PRODUCTO = 'PS' AND F.SUBTIPO_PRODUCTO = 'PS' AND F.COD_LARGO_PROD LIKE '%-004%'
        THEN 'SEMITERMINADO'
        WHEN F.ALMACEN = 'CL1' AND F.TIPO_PRODUCTO = 'PS' AND F.SUBTIPO_PRODUCTO = 'PS' AND (F.COD_LARGO_PROD LIKE '%-002%' OR F.COD_LARGO_PROD LIKE '%-009%') AND CB.TIPO_BASE = 'PR'
        THEN 'UDS MUESTRA ACONDICIONADO'
        WHEN F.ALMACEN = 'CL1' AND F.TIPO_PRODUCTO = 'PR' AND F.SUBTIPO_PRODUCTO = 'MUE'
        THEN 'UDS MUESTRA ACONDICIONADO'
        WHEN F.ALMACEN = 'CL1' AND F.TIPO_PRODUCTO = 'PT' AND F.SUBTIPO_PRODUCTO = 'PT'
        THEN 'UDS VENTA ACONDICIONADO'
        WHEN F.ALMACEN = 'CL1' AND F.TIPO_PRODUCTO = 'PS' AND F.SUBTIPO_PRODUCTO = 'PS' AND (F.COD_LARGO_PROD LIKE '%-002%' OR F.COD_LARGO_PROD LIKE '%-009%') AND CB.TIPO_BASE = 'PT'
        THEN 'UDS VENTA ACONDICIONADO'
        ----------------------------------------- ALMACEN CL1T --------------------------------------------------
        WHEN F.ALMACEN = 'CL1T' AND F.TIPO_PRODUCTO = 'PR' AND CCL1.COD_LARGO_PROD IS NOT NULL 
        THEN 'UDS MUESTRA MANIPULADO'
        WHEN F.ALMACEN = 'CL1T' AND F.TIPO_PRODUCTO = 'PT' AND CCL1.COD_LARGO_PROD IS NOT NULL 
        THEN 'UDS VENTA MANIPULADO'
        WHEN F.ALMACEN = 'CL1T' AND F.TIPO_PRODUCTO = 'PS' AND F.SUBTIPO_PRODUCTO = 'BLK'
        THEN 'KGS FABRICADOS'
        WHEN F.ALMACEN = 'CL1T' AND F.TIPO_PRODUCTO = 'PS' AND F.SUBTIPO_PRODUCTO = 'PS'
        THEN 'SEMITERMINADO'
        WHEN F.ALMACEN = 'CL1T' AND F.TIPO_PRODUCTO = 'PR' AND F.SUBTIPO_PRODUCTO = 'MUE' --AND (F.COD_LARGO_PROD LIKE '%-002%' OR F.COD_LARGO_PROD LIKE '%-009%')
        THEN 'UDS MUESTRA ACONDICIONADO'
        WHEN F.ALMACEN = 'CL1T' AND F.TIPO_PRODUCTO = 'PT' AND F.SUBTIPO_PRODUCTO = 'PT' --AND (F.COD_LARGO_PROD LIKE '%-002%' OR F.COD_LARGO_PROD LIKE '%-009%')
        THEN 'UDS VENTA ACONDICIONADO'
        ELSE ''
    END)
    END)) AS CLASIFICACION_FAB
FROM FAB F
LEFT JOIN COD_BASE CB ON CB.COD_BASE = REGEXP_REPLACE(F.COD_LARGO_PROD, '-00[0-9]$', '')
LEFT JOIN COD_CL1 CCL1 ON REGEXP_REPLACE(CCL1.COD_LARGO_PROD, '-00[0-9]$', '') = F.COD_LARGO_PROD
LEFT JOIN ANL_AUX_IND_CLASIFICACION_FABRICA AUX ON TRIM(F.COD_LARGO_PROD) = TRIM(AUX.COD_PROD_LARGO) AND F.ALMACEN = AUX.ALMACEN AND F.FECHA_FINALIZACION> 20260000 AND F.FECHA_FINALIZACION< 20260701
)
; 



COMMIT;


END INDUSTRIAL_UNIDADES_FABRICADAS;


