create or replace PROCEDURE "INDUSTRIAL_NIVELES_SERVICIO" IS

--Realizado por Ángel Jesús Calzas Durán
--Versión: 7
--Fecha: 3/7/2026

-- DEFINICIÓN DE VARIABLES
V_SQL                   VARCHAR2(32000);
V_ANIOMES_ACT           NUMBER;
V_ANIOMES_ANT           NUMBER;
V_ANIOMES_ANT_DIA       NUMBER;

-- DEFINICIÓN DE CURSORES
CURSOR C_ANIOMES_ANT IS 
SELECT TO_NUMBER(to_char(ADD_MONTHS(SYSDATE,-1),'YYYYMM')) V_ANIOMES
FROM DUAL
;
CURSOR C_ANIOMES_ACT IS 
SELECT TO_NUMBER(to_char(SYSDATE,'YYYYMM')) V_ANIOMES
FROM DUAL
;
CURSOR C_ANIOMES_ANT_ULTIMO_DIA IS 
SELECT TO_NUMBER(to_char(last_day(ADD_MONTHS(SYSDATE,-1)),'YYYYMMDD')) V_ANIOMES
FROM DUAL
;
CURSOR C_CANTIDAD_ENVIADA IS
SELECT R.NUM_ORDEN, R.NUMERO_LOTE, R.COD_CORTO_PROD, R.FECHA_FINALIZACION_LIB, R.USUARIO, F.VALOR_METRICA, F.CLASIFICACION_FABRICA
FROM ANL_IND_NIVELES_SERVICIO R
INNER JOIN anl_ind_unidades_fabricadas F
ON R.NUM_ORDEN||'WO'=F.NUM_ORDEN AND R.NUMERO_LOTE=F.NUM_LOTE AND R.COD_CORTO_PROD=F.COD_CORTO_PROD AND R.FECHA_FINALIZACION_LIB=F.FECHA_FINALIZACION AND R.USUARIO=F.USUARIO
AND F.METRICA='Uds Fabricadas'
WHERE R.FLG_ESTADO='CERRADO'
AND SUBSTR(R.FECHA_FINALIZACION_LIB,1,6)>=to_char(ADD_MONTHS(SYSDATE,-4), 'YYYYMM') OR F.CLASIFICACION_FABRICA IS NOT NULL
;

-------------------------------------------------
-- Comienzo de la lógica
-------------------------------------------------

BEGIN

-- Establecer el mes actual
OPEN C_ANIOMES_ANT;
OPEN C_ANIOMES_ACT;
OPEN C_ANIOMES_ANT_ULTIMO_DIA;

FETCH C_ANIOMES_ACT INTO V_ANIOMES_ACT;
FETCH C_ANIOMES_ANT INTO V_ANIOMES_ANT;
FETCH C_ANIOMES_ANT_ULTIMO_DIA INTO V_ANIOMES_ANT_DIA;

----Actualizar RUTAS_ORDENES
CLABS_ANL_PRO.INDUSTRIAL_RUTAS_ORDENES;

--Se realiza el cálculo de órdenes abiertas el día 1 de cada mes
IF EXTRACT(DAY FROM SYSDATE)=1 THEN

-- Insertamos las ordenes abiertas del mes
V_SQL:='
INSERT INTO ANL_IND_NIVELES_SERVICIO (NUM_ORDEN, ESTADO, FECHA_ANALISIS, CANTIDAD_ORDENADA, FECHA_INICIAL, FECHA_SOLICITADA, 
                                      FECHA_DISPONIBILIDAD, FECHA_FINALIZACION, FECHA_ORDEN, FLG_ESTADO, PROVEEDORES,
                                      COD_CORTO_PROD, COD_LARGO_PROD, ALMACEN, NUMERO_LOTE, LOCAL_PRODUCT_NAME, BRAND, REGULATORY_STATUS,
                                      UNIDADES_METRICAS, USUARIO, TIPO_PRODUCTO, FASE, NUMERO_UNIDAD, NUMERO_ACTIVO, DESC_ACTIVO, SUBTIPO_PRODUCTO) 
                                      
SELECT 
ORD.WADOCO NUM_ORDEN,
ORD.WASRST ESTADO,
to_number(CONCAT('||V_ANIOMES_ACT||',''01'')) AS FECHA_ANALISIS,
ORD.WAUORG/10000 CANTIDAD_ORDENADA,
to_number(to_char(date_conversion.from_julian(ORD.WASTRT),''YYYYMMDD'')) as FECHA_INICIAL,
to_number(to_char(date_conversion.from_julian(ORD.WADRQJ),''YYYYMMDD'')) as FECHA_SOLICITADA,
to_number(to_char(date_conversion.from_julian(ORD.WADPL),''YYYYMMDD'')) as FECHA_DISPONIBILIDAD, 
to_number(to_char(date_conversion.from_julian(ORD.WASTRX),''YYYYMMDD'')) AS FECHA_FINALIZACION,
to_number(to_char(date_conversion.from_julian(ORD.WATRDJ),''YYYYMMDD'')) AS FECHA_ORDEN,
''ABIERTO'' AS FLG_ESTADO,
PROV.PROVEEDORES,
TRIM(WAITM) AS COD_CORTO_PROD, 
TRIM(WALITM) AS COD_LARGO_PROD, 
TRIM(WAMCU) AS ALMACEN, 
NVL(TRIM(WALOTN),''DESC'') AS NUMERO_LOTE,
trim(NOM.IMDSC1)|| '' '' || trim(NOM.IMDSC2) AS LOCAL_PRODUCT_NAME, 
NOM.IMSRP1 AS BRAND, 
NOM.IMSRP6 AS REGULATORY_STATUS,
ORD.WAUOM AS UNIDADES_METRICAS,
ORD.WAUSER AS USUARIO,
NOM.IMPRP1 AS TIPO_PRODUCTO,
RUT.FASE,
RUT.NUMERO_UNIDAD,
RUT.NUMERO_ACTIVO,
RUT.DESC_ACTIVO,
NOM.IMPRP2 AS SUBTIPO_PRODUCTO
FROM STG_JDE_IFCSA_F4801 ORD
LEFT JOIN STG_JDE_IFCSA_F4101_ADT NOM
ON ORD.WAITM = NOM.IMITM
LEFT JOIN 
(
SELECT A.WLDOCO,  LISTAGG(A.WLVEND||'' - ''||TRIM(B.ABALPH), ''; '') AS PROVEEDORES 
FROM 
"CLABS_STG_PRO"."STG_JDE_IFCSA_F3112" A
LEFT JOIN "CLABS_STG_PRO"."STG_JDE_IFCSA_F0101" B
ON A.WLVEND=B.ABAN8
where WLVEND<>0
GROUP BY WLDOCO
) PROV
ON ORD.WADOCO=PROV.WLDOCO
LEFT JOIN ANL_IND_RUTAS_ORDENES RUT
ON ORD.WADOCO=RUT.NUM_ORDEN AND RUT.FASE=205
WHERE 
(CASE WHEN ORD.WASRST<>'' '' THEN TO_NUMBER(ORD.WASRST) END)<=''65''
AND TRIM(WAMCU) IN (''TOR'',''TORT'',''CL1'',''CL1T'',''CL2'')
'
;

EXECUTE IMMEDIATE V_SQL;
COMMIT;

END IF;

-- Cálculamos las órdenes cerradas del mes
-- Insertamos las órdenes cerradas del mes que no están aún
V_SQL:='
INSERT INTO ANL_IND_NIVELES_SERVICIO (NUM_ORDEN, ESTADO, FECHA_ANALISIS, CANTIDAD_ORDENADA, FECHA_INICIAL, FECHA_SOLICITADA, FECHA_DISPONIBILIDAD, FECHA_FINALIZACION, FECHA_ORDEN, UBICACION,
                                      COD_CORTO_PROD, COD_LARGO_PROD, ALMACEN, TIPO_PRODUCTO, CANTIDAD_ENVIADA, CANTIDAD_RECHAZADA, NUMERO_LOTE, UNIDADES_METRICAS, USUARIO, 
                                      LOCAL_PRODUCT_NAME, BRAND, REGULATORY_STATUS, ESTADO_CALIDAD_JDE, FLG_ESTADO, FLG_CIERRE, PROVEEDORES,
                                      FASE, NUMERO_UNIDAD, NUMERO_ACTIVO, DESC_ACTIVO, SUBTIPO_PRODUCTO, FECHA_FINALIZACION_LIB) 
                                      
SELECT 
ORD.WADOCO NUM_ORDEN,
ORD.WASRST ESTADO,
'||V_ANIOMES_ANT_DIA||' AS FECHA_ANALISIS,
ORD.WAUORG/10000 CANTIDAD_ORDENADA,
to_number(to_char(date_conversion.from_julian(ORD.WASTRT),''YYYYMMDD'')) as FECHA_INICIAL,
to_number(to_char(date_conversion.from_julian(ORD.WADRQJ),''YYYYMMDD'')) as FECHA_SOLICITADA,
to_number(to_char(date_conversion.from_julian(ORD.WADPL),''YYYYMMDD'')) as FECHA_DISPONIBILIDAD, 
to_number(to_char(date_conversion.from_julian(ORD.WASTRX),''YYYYMMDD'')) AS FECHA_FINALIZACION,
to_number(to_char(date_conversion.from_julian(ORD.WATRDJ),''YYYYMMDD'')) AS FECHA_ORDEN,
ORD.WALOCN AS UBICACION,
LIB.COD_CORTO_PROD, 
LIB.COD_LARGO_PROD, 
LIB.ALMACEN, 
LIB.TIPO_PRODUCTO, 
CANT.VALOR_METRICA AS CANTIDAD_ENVIADA,
/*LIB.CANTIDAD_ENVIADA,*/
LIB.CANTIDAD_RECHAZADA,
LIB.NUMERO_LOTE,
LIB.UNIDADES_METRICAS, 
LIB.USUARIO,
LIB.LOCAL_PRODUCT_NAME, 
LIB.BRAND, 
LIB.REGULATORY_STATUS, 
LIB.ESTADO_CALIDAD_JDE,
''CERRADO'' AS FLG_ESTADO,
0 AS FLG_CIERRE,
PROV.PROVEEDORES,
RUT.FASE,
RUT.NUMERO_UNIDAD,
RUT.NUMERO_ACTIVO,
RUT.DESC_ACTIVO,
LIB.SUBTIPO_PRODUCTO,
LIB.FECHA_FINALIZACION_LIB
FROM STG_JDE_IFCSA_F4801 ORD
LEFT JOIN ANL_IND_RUTAS_ORDENES RUT
ON ORD.WADOCO=RUT.NUM_ORDEN AND RUT.FASE=205
LEFT JOIN 
(
SELECT A.WLDOCO,  LISTAGG(A.WLVEND||'' - ''||TRIM(B.ABALPH), ''; '') AS PROVEEDORES 
FROM 
"CLABS_STG_PRO"."STG_JDE_IFCSA_F3112" A
LEFT JOIN "CLABS_STG_PRO"."STG_JDE_IFCSA_F0101" B
ON A.WLVEND=B.ABAN8
where WLVEND<>0
GROUP BY WLDOCO
) PROV
ON ORD.WADOCO=PROV.WLDOCO
LEFT JOIN 
(
SELECT 
COD_CORTO_PROD, 
COD_LARGO_PROD, 
ALMACEN, 
TIPO_PRODUCTO, 
NUM_ORDEN,
SUM(CASE WHEN ESTADO_JDE = ''IC'' THEN CANTIDAD END) AS CANTIDAD_ENVIADA,
SUM(CASE WHEN ESTADO_JDE = ''IS'' THEN CANTIDAD END) AS CANTIDAD_RECHAZADA,
NUMERO_LOTE,
ANIO_MES_MOVIMIENTO,
UNIDADES_METRICAS, 
USUARIO,
LOCAL_PRODUCT_NAME, 
BRAND, 
REGULATORY_STATUS, 
ESTADO_CALIDAD_JDE,
SUBTIPO_PRODUCTO,
FECHA_FINALIZACION_LIB
FROM 
(
SELECT 
TRIM(ILITM) COD_CORTO_PROD, 
TRIM(ILLITM) COD_LARGO_PROD, 
TRIM(ILMCU) ALMACEN, 
IMPRP1 AS TIPO_PRODUCTO, 
ILDOCO AS NUM_ORDEN,
ILTRQT/10000 CANTIDAD,
NVL(TRIM(ILLOTN),''DESC'') NUMERO_LOTE,
to_number(to_char(date_conversion.from_julian(ILDGL), ''YYYYMM'')) AS ANIO_MES_MOVIMIENTO,
TRIM(ILTRUM) UNIDADES_METRICAS, 
TRIM(iluser) as USUARIO, 
TRIM(ILDCT) AS ESTADO_JDE,
trim(NOM.IMDSC1)|| '' '' || trim(NOM.IMDSC2) AS LOCAL_PRODUCT_NAME, 
NOM.IMSRP1 AS BRAND, 
NOM.IMSRP6 AS REGULATORY_STATUS, 
TRIM(ILLOTS) AS ESTADO_CALIDAD_JDE,
IMPRP2 AS SUBTIPO_PRODUCTO,
to_number(to_char(date_conversion.from_julian(ILDGL), ''YYYYMMDD'')) AS FECHA_FINALIZACION_LIB
FROM STG_JDE_IFCSA_F4111 LIMS 
LEFT JOIN STG_JDE_IFCSA_F4101_ADT NOM
ON ILLITM = IMLITM
)
WHERE 
ESTADO_JDE  IN (''IC'',''IS'')
AND ANIO_MES_MOVIMIENTO<='||V_ANIOMES_ANT||'
GROUP BY 
COD_CORTO_PROD, 
COD_LARGO_PROD, 
ALMACEN, 
TIPO_PRODUCTO, 
NUM_ORDEN,
NUMERO_LOTE,
ANIO_MES_MOVIMIENTO,
UNIDADES_METRICAS, 
USUARIO,
LOCAL_PRODUCT_NAME, 
BRAND, 
REGULATORY_STATUS, 
ESTADO_CALIDAD_JDE,
SUBTIPO_PRODUCTO,
FECHA_FINALIZACION_LIB
) LIB
ON ORD.WADOCO=LIB.NUM_ORDEN AND ORD.WAITM=LIB.COD_CORTO_PROD
LEFT JOIN 
(SELECT * FROM 
anl_ind_unidades_fabricadas
where METRICA=''Uds Fabricadas'') CANT
ON CANT.NUM_ORDEN=LIB.NUM_ORDEN||''WO'' AND CANT.COD_LARGO_PROD=LIB.COD_LARGO_PROD AND CANT.NUM_LOTE=LIB.NUMERO_LOTE AND CANT.FECHA_FINALIZACION=LIB.FECHA_FINALIZACION_LIB
WHERE 
ORD.WADOCO IN 
(
SELECT DISTINCT ORD.WADOCO
FROM STG_JDE_IFCSA_F4801 ORD
LEFT JOIN 
STG_JDE_IFCSA_F4111 LIB
ON ORD.WADOCO=LIB.ILDOCO
WHERE TRIM(LIB.ILDCT)=''IC'' AND TRIM(ILMCU) IN (''TOR'',''TORT'',''CL1'',''CL1T'',''CL2'') AND to_number(to_char(date_conversion.from_julian(ILDGL), ''YYYYMM''))<='||V_ANIOMES_ANT||'
--------------------------NEW-------------------------
AND to_number(to_char(date_conversion.from_julian(WADCG), ''YYYYMM''))>=TO_NUMBER(to_char(ADD_MONTHS(SYSDATE,-2),''YYYYMM''))
AND (CASE WHEN ORD.WASRST<>'' '' THEN TO_NUMBER(ORD.WASRST) END) >= 80
AND ORD.WADOCO||''-''||NVL(TRIM(LIB.ILLOTN),''DESC'')||''-''||TRIM(LIB.ILMCU)
NOT IN 
(
SELECT DISTINCT NUM_ORDEN||''-''||NUMERO_LOTE||''-''||ALMACEN FROM 
ANL_IND_NIVELES_SERVICIO
WHERE FLG_ESTADO=''CERRADO''
)
----------------------------------------------------
)
AND (CASE WHEN ORD.WASRST<>'' '' THEN TO_NUMBER(ORD.WASRST) END) >= 80
AND ORD.WADOCO||''-''||LIB.NUMERO_LOTE||''-''||LIB.ALMACEN||''-''||LIB.FECHA_FINALIZACION_LIB
NOT IN 
(
SELECT DISTINCT NUM_ORDEN||''-''||NUMERO_LOTE||''-''||ALMACEN||''-''||FECHA_FINALIZACION_LIB FROM 
ANL_IND_NIVELES_SERVICIO
WHERE FLG_ESTADO=''CERRADO''
)
ORDER BY ORD.WADOCO DESC 
'
;

EXECUTE IMMEDIATE V_SQL;
COMMIT;

-- Marcamos las ordenes que han sido cerradas en el mes que estaban abiertas en el mes anterior

V_SQL := '
UPDATE ANL_IND_NIVELES_SERVICIO 
SET FLG_CIERRE =  1
WHERE NUM_ORDEN IN
(
SELECT DISTINCT NUM_ORDEN FROM 
ANL_IND_NIVELES_SERVICIO
WHERE FLG_ESTADO=''ABIERTO'' AND FECHA_ANALISIS=to_number(CONCAT('||V_ANIOMES_ANT||',''01''))
)
AND FLG_ESTADO=''CERRADO'' AND FECHA_ANALISIS='||V_ANIOMES_ANT_DIA||'
'
;

EXECUTE IMMEDIATE V_SQL;
COMMIT;     

-- Actualizamos la cantidad enviada porque puede cambiar tras cerrar la orden y clasificacion fabrica
FOR R IN C_CANTIDAD_ENVIADA LOOP

UPDATE ANL_IND_NIVELES_SERVICIO 
SET CANTIDAD_ENVIADA = R.VALOR_METRICA
WHERE NUM_ORDEN = R.NUM_ORDEN
AND NUMERO_LOTE = R.NUMERO_LOTE
AND COD_CORTO_PROD = R.COD_CORTO_PROD
AND FECHA_FINALIZACION_LIB = R.FECHA_FINALIZACION_LIB
AND USUARIO=R.USUARIO
;

UPDATE ANL_IND_NIVELES_SERVICIO 
SET CLASIFICACION_FABRICA = R.CLASIFICACION_FABRICA
WHERE NUM_ORDEN = R.NUM_ORDEN
AND NUMERO_LOTE = R.NUMERO_LOTE
AND COD_CORTO_PROD = R.COD_CORTO_PROD
AND FECHA_FINALIZACION_LIB = R.FECHA_FINALIZACION_LIB
AND USUARIO=R.USUARIO
;

COMMIT; 

END LOOP;-- SE CIERRA EL LOOP DEL CURSOR



--Cerrar cursores

CLOSE C_ANIOMES_ANT;
CLOSE C_ANIOMES_ACT;
CLOSE C_ANIOMES_ANT_ULTIMO_DIA;



END INDUSTRIAL_NIVELES_SERVICIO;
